export const contantActions = {
  SET_BACKGROUND_COLOR: "set_background_color",
  SET_TOP: "set_top",
  SET_LEFT: "set_left",
  SET_BORDER_COLOR: "set_border_color",
  SET_BORDER_RADIUS: "set_border_radius",
  SET_BORDER_STYLE: "set_border_style",
  SET_MAGRIN: "set_margin",
  SET_PADDING: "set_padding",
  SET_HEIGHT: "set_height",
  SET_WIDTH: "set_width",
  SET_COLOR: "set_color",
  SET_FONT_SIZE: "set_font_size",
  SET_FONT_FAMILY: "set_font_family",
  SET_ID_ITEM: "set_id",
};
