import uuid from "react-uuid";

export const DefaultItemInGridTemplate2 = [
  {
    type: "img",
    left: 0,
    top: 0,
    width: "100%",
    height: 500,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://images.unsplash.com/photo-1497864149936-d3163f0c0f4b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
    styles: {},
  },
  {
    type: "img",
    left: "60%",
    top: "5%",
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://o.remove.bg/downloads/6245ca15-7a91-4cb6-8f30-dad74f42b26c/top-10-cong-cu-viet-code-removebg-preview.png",
    styles: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
    },
  },
  {
    type: "input",
    left: 140,
    top: 200,
    width: 400,
    height: 50,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "Enter title",
    styles: {
      backgroundColor: "transparent",
      fontSize: 24,
      textAlign: "center",
      border: "none",
      color: "#fff",
      fontFamily: "Poppins",
      lineHeight: "26px",
    },
  },
  // {
  //   type1: "img",
  //   type2: "input",
  //   type3: "img",
  //   type4: "input",
  //   left: 0,
  //   top: 100,
  //   width: 200,
  //   height: 50,
  //   id: uuid(),
  //   inGrid: true,
  //   isMulti: true,
  //   numberComponents: 4,
  //   styles: {
  //     backgroundColor: "red",
  //   },
  // },

  // {
  //   type: "input",
  //   left: 100,
  //   top: 50,
  //   width: 200,
  //   height: 50,
  //   id: uuid(),
  //   inGrid: true,
  //   isMulti: false,
  // },
  // {
  //   type: "input",
  //   left: 300,
  //   top: 300,
  //   width: 400,
  //   height: 50,
  //   id: uuid(),
  //   inGrid: true,
  //   isMulti: false,
  // },
];
