import uuid from "react-uuid";
import backGroundHeader02 from "~/assets/img/backGroundHeader02.png";
import {
  GrFacebookOption,
  GrInstagram,
  GrGithub,
  GrLinkedin,
  GrYoutube,
} from "react-icons/gr";

const leftDefaultText = 50;
const leftDefaultTitle = 100;

export const DefaultItemInGridTemplate2 = [
  //header
  {
    type: "img",
    left: 0,
    top: 0,
    width: "100%",
    height: 502,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://images.unsplash.com/photo-1497864149936-d3163f0c0f4b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
    styles: {
      backgroundColor: "rgba(0,0,0,0,.3)",
    },
  },
  //about
  {
    type: "div",
    left: 0,
    top: 500,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    styles: {
      backgroundColor: "#182d47",
      border: "none",
    },
  },
  //service
  {
    type: "div",
    left: 0,
    top: 1000,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styles: {
      backgroundColor: "#091d35",
      border: "none",
    },
  },
  //feedback
  {
    type: "div",
    left: 0,
    top: 1500,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    styles: {
      backgroundColor: "#182d47",
      border: "none",
    },
  },
  // your project
  {
    type: "div",
    left: 0,
    top: 2000,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styles: {
      backgroundColor: "#091d35",
      border: "none",
    },
  },
  //footer
  {
    type: "div",
    left: 0,
    top: 2500,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styles: {
      backgroundColor: "#182d47",
      border: "none",
    },
  },
  //end open each part in portfolio
  //begin header
  {
    type: "img",
    left: "60%",
    top: 80,
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/uo3V1fn.png",
    styles: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
    },
  },
  {
    type: "input",
    left: leftDefaultTitle,
    top: 150,
    width: 400,
    height: 50,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styles: {
      backgroundColor: "transparent",
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      border: "none",
      color: "#DC143C",
      fontFamily: "Poppins",
      lineHeight: "26px",
      border: "1px solid #ccc",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 250,
    width: 500,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    styles: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#FFFFE0",
      fontFamily: "Poppins",
      lineHeight: "26px",
      border: "1px solid #ccc",
    },
  },
  {
    type: "button",
    left: 12,
    top: 12,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    styles: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#FF0000",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
    },
  },
  //end header
  //begin about
  {
    type: "img",
    left: "60%",
    top: 560,
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/MCXD87T.png",
    styles: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
    },
  },
  {
    type: "button",
    left: leftDefaultTitle,
    top: 650,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About",
    styles: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "#6A5ACD",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "UpperCase",
      border: "1px solid #ccc",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 740,
    width: 500,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styles: {
      fontWeight: "bold",
      color: "#fff",
      backgroundColor: "transparent",
      // border: "none",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
    },
  },
  //end about
  //begin service
  {
    type: "input",
    left: "50%",
    top: 1040,
    width: 400,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your Offered Services]",
    styles: {
      fontWeight: "bold",
      color: "#6A5ACD",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1120,
    width: 600,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styles: {
      color: "#fff",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
    },
  },
  {
    type1: "img",
    type2: "input",
    left: 0,
    top: 1200,
    width: "100%",
    height: 300,
    id: uuid(),
    idItem1: uuid(),
    idItem2: uuid(),
    idItem3: uuid(),
    idItem4: uuid(),
    idItem5: uuid(),
    idItem6: uuid(),
    idItem7: uuid(),
    idItem8: uuid(),
    inGrid: true,
    isMulti: true,
    numberComponents: 8,
    stylesComponentMulti: {
      backgroundColor: "transparent",
    },
  },
  //end service
  //begin feedback
  {
    type: "img",
    left: leftDefaultText,
    top: 1540,
    width: 400,
    height: 400,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    styles: {
      fontWeight: "bold",
      color: "#c9ab7a",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      height: 400,
    },
  },
  {
    type: "input",
    left: "55%",
    top: 1540,
    width: 300,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "[Feedback from client]",
    styles: {
      fontWeight: "bold",
      color: "#c9ab7a",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1620,
    width: 400,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your slogan>",
    styles: {
      color: "#fff",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
    },
  },
  //end feedback
  //begin your project
  {
    type: "input",
    left: "50%",
    top: 2040,
    width: 400,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styles: {
      fontWeight: "bold",
      color: "#b3073c",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
    },
  },
  {
    type: "input",
    left: "50%",
    top: 2120,
    width: 600,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Technology used>",
    styles: {
      color: "#fff",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
    },
  },
  {
    type1: "img",
    type2: "input",
    type3: "img",
    type4: "input",
    left: 0,
    top: 2250,
    width: "100%",
    height: 300,
    id: uuid(),
    idItem1: uuid(),
    idItem2: uuid(),
    idItem3: uuid(),
    idItem4: uuid(),
    inGrid: true,
    isMulti: true,
    numberComponents: 4,
    stylesComponentMulti: {
      backgroundColor: "transparent",
    },
  },
  //end your project
  //begin footer
  {
    type: "input",
    left: "50%",
    top: 2540,
    width: 250,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Looking ForWard to working with everyone!",
    styles: {
      fontWeight: "bold",
      color: "#FFF8DC",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      lineHeight: "32px",
      textTransform: "upperCase",
    },
  },
  {
    type: "img",
    left: "50%",
    top: 2680,
    width: 200,
    height: 250,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.imgur.com/PAvCNbh.png",
    styles: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 2880,
    width: 300,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
    },
  },
  {
    type: "button",
    left: "70%",
    top: 2600,
    width: 200,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "About",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
      textTransform: "upperCase",
    },
  },
  {
    type: "input",
    left: "64%",
    top: 2680,
    width: 320,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Address detail,your number]",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
    },
  },

  {
    type: "a",
    left: "62%",
    top: 2880,
    width: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    href: {
      name: "facebook",
      href: "#",
    },
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: 14,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
  },
  {
    type: "a",
    left: "74%",
    top: 2880,
    width: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    href: {
      name: "Instagram",
      href: "#",
    },
    valueItem: "[Detail contact, number phone]",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: 14,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
  },
  {
    type: "a",
    left: "86%",
    top: 2880,
    width: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    href: {
      name: "Youtube",
      href: "#",
    },
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: 14,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
  },

  //end footer
];

export const DefaultItemInGridTemplate3 = [
  //header

  //about

  //projects

  //eduction

  // other project

  //footer

  //end open each part in portfolio
  //begin header
  {
    type: "img",
    left: "50%",
    top: 100,
    width: 600,
    height: 250,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/F5445KH/icon-removebg-preview.png",
    styles: {
      backgroundColor: "transparent",
      borderColor: "transparent",
    },
  },
  {
    type: "input",
    left: "70%",
    top: 380,
    width: 500,
    height: 80,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<About>",
    center: true,
    styles: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#000",
      fontFamily: "Poppins",
      lineHeight: "26px",
      border: "1px solid #ccc",
      boxShadow: "14px 17px 115px 0px rgba(0,0,0,0.75)",
      zIndex: -100,
    },
  },
  {
    type: "button",
    left: "50%",
    top: 12,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    center: true,
    styles: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#000",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
    },
  },
  {
    type: "input",
    left: "10%",
    top: 100,
    width: 400,
    height: 50,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styles: {
      backgroundColor: "transparent",
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      border: "none",
      color: "rgb(255, 0, 255)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      border: "3px outset  rgb(255, 69, 0)",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
      borderRadius: "100px",
      fontWeight: "bold",
      textTransform: "uppercase",
    },
  },
  {
    type: "input",
    left: "70%",
    top: 300,
    width: 500,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    center: true,
    styles: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#800000",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "20px",
      border: "1px outset  rgb(255, 69, 0)",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
    },
  },

  //end header
  //begin about
  {
    type: "img",
    left: leftDefaultText + 150,
    top: 560,
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/CnXLkqg/Pngtree-cartoon-hand-drawn-online-education-4986516.png",
    styles: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
    },
  },
  {
    type: "button",
    left: "55%",
    top: 650,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About",
    styles: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "#6A5ACD",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "UpperCase",
      border: "3px outset #DC143C",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  {
    type: "input",
    left: "40%",
    top: 740,
    width: 500,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styles: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      // border: "none",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  //end about
  //begin projects
  {
    type: "input",
    left: "50%",
    top: 1040,
    width: 400,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styles: {
      fontWeight: "bold",
      color: "#6A5ACD",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
      textTransform: "uppercase",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1120,
    width: 600,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styles: {
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  {
    type1: "img",
    type2: "input",
    left: 0,
    top: 1200,
    width: "100%",
    height: 450,
    id: uuid(),
    idItem1: uuid(),
    idItem2: uuid(),
    idItem3: uuid(),
    idItem4: uuid(),
    idItem5: uuid(),
    idItem6: uuid(),
    idItem7: uuid(),
    idItem8: uuid(),
    inGrid: true,
    isMulti: true,
    numberComponents: 8,
    stylesComponentMulti: {
      backgroundColor: "#FFC0CB",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  //end projects
  //begin education
  {
    type: "img",
    left: "50%",
    top: 1520,
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/KzzV8qS/Pngtree-network-education-online-education-illustration-6187862.png",
    styles: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
    },
  },
  {
    type: "input",
    left: leftDefaultTitle,
    top: 1540,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Education",
    styles: {
      fontWeight: "bold",
      color: "#c9ab7a",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 1620,
    width: 300,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Details major>",
    styles: {
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  {
    type: "input",
    left: "70%",
    top: 1540,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About work",
    styles: {
      fontWeight: "bold",
      color: "#c9ab7a",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "input",
    left: "65%",
    top: 1620,
    width: 300,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Details work>",
    styles: {
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1900,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Your feeling>",
    styles: {
      color: "#ccc",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
    },
  },
  //end education
  //begin other project
  {
    type: "input",
    left: "62%",
    top: 2040,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Other projects",
    styles: {
      fontWeight: "bold",
      color: "#b3073c",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "img",
    left: leftDefaultText,
    top: 2120,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,

    styles: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
    },
  },
  {
    type: "img",
    left: 200 + leftDefaultText + 24,
    top: 2080,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,

    styles: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
    },
  },
  {
    type: "img",
    left: 200 + leftDefaultText + 24,
    top: 2250,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,

    styles: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
    },
  },

  {
    type: "input",
    left: "60%",
    top: 2140,
    width: 250,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Technology used>",
    styles: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 2240,
    width: 270,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Field of work>",
    styles: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 2340,
    width: 370,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Describes>",
    styles: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "12px",
    },
  },
  //end your project
  //begin footer
  {
    type: "input",
    left: "50%",
    top: 2540,
    width: 250,
    height: 50,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Contact me",
    styles: {
      fontWeight: "bold",
      color: "#b3073c",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "img",
    left: "50%",
    top: 2680,
    width: 300,
    height: 250,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/dg8wwp3/Pngtree-contact-us-flat-design-style-5874427.png",
    styles: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 2680,
    width: 300,
    height: 284,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styles: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
      borderRadius: 24,
    },
  },
  {
    type: "button",
    left: "70%",
    top: 2700,
    width: 200,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Your social networks>",
    styles: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
      borderRadius: 24,
    },
  },

  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: "70%",
    top: 2850,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Facebook",
      Component: <GrFacebookOption />,
    },
    styles: {
      left: 500,
      top: 2670,
      color: "#kkk",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: "76%",
    top: 2850,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Instagram",
      Component: <GrInstagram />,
    },
    styles: {
      left: 500,
      top: 2670,
      color: "#kkk",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: "82%",
    top: 2850,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Github",
      Component: <GrGithub />,
    },
    styles: {
      left: 500,
      top: 2670,
      color: "#kkk",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: "88%",
    top: 2850,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Youtube",
      Component: <GrYoutube />,
    },
    styles: {
      left: 500,
      top: 2670,
      color: "#kkk",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },

  //end footer
];
