import uuid from "react-uuid";
const leftDefaultText = 50;
const leftDefaultTitle = 100;
export const DefaultItemInGridTemplate2 = [
  //header
  {
    type: "img",
    left: 0,
    top: 0,
    width: "100%",
    height: 502,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://images.unsplash.com/photo-1497864149936-d3163f0c0f4b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
    styles: {
      backgroundColor: "rgba(0,0,0,0,.3)",
    },
  },
  //about
  {
    type: "div",
    left: 0,
    top: 500,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    styles: {
      backgroundColor: "#182d47",
      border: "none",
    },
  },
  //service
  {
    type: "div",
    left: 0,
    top: 1000,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styles: {
      backgroundColor: "#091d35",
      border: "none",
    },
  },
  //feedback
  {
    type: "div",
    left: 0,
    top: 1500,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    styles: {
      backgroundColor: "#182d47",
      border: "none",
    },
  },
  // your project
  {
    type: "div",
    left: 0,
    top: 2000,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styles: {
      backgroundColor: "#091d35",
      border: "none",
    },
  },
  //footer
  {
    type: "div",
    left: 0,
    top: 2500,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styles: {
      backgroundColor: "#182d47",
      border: "none",
    },
  },
  //end open each part in portfolio
  //begin header
  {
    type: "img",
    left: "60%",
    top: 80,
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/uo3V1fn.png",
    styles: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
    },
  },
  {
    type: "input",
    left: leftDefaultTitle,
    top: 150,
    width: 400,
    height: 50,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styles: {
      backgroundColor: "transparent",
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      border: "none",
      color: "#DC143C",
      fontFamily: "Poppins",
      lineHeight: "26px",
      border: "1px solid #ccc",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 250,
    width: 500,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    styles: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#FFFFE0",
      fontFamily: "Poppins",
      lineHeight: "26px",
      border: "1px solid #ccc",
    },
  },
  {
    type: "button",
    left: 12,
    top: 12,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    styles: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#FF0000",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
    },
  },
  //end header
  //begin about
  {
    type: "img",
    left: "60%",
    top: 560,
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/MCXD87T.png",
    styles: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
    },
  },
  {
    type: "button",
    left: leftDefaultTitle,
    top: 650,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About",
    styles: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "#6A5ACD",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "UpperCase",
      border: "1px solid #ccc",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 740,
    width: 500,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styles: {
      fontWeight: "bold",
      color: "#fff",
      backgroundColor: "transparent",
      // border: "none",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
    },
  },
  //end about
  //begin service
  {
    type: "input",
    left: "50%",
    top: 1040,
    width: 400,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your Offered Services]",
    styles: {
      fontWeight: "bold",
      color: "#6A5ACD",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1120,
    width: 600,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styles: {
      color: "#fff",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
    },
  },
  {
    type1: "img",
    type2: "input",
    left: 0,
    top: 1200,
    width: "100%",
    height: 300,
    id: uuid(),
    inGrid: true,
    isMulti: true,
    numberComponents: 8,
    stylesComponentMulti: {
      backgroundColor: "transparent",
    },
  },
  //end service
  //begin feedback
  {
    type: "img",
    left: leftDefaultText,
    top: 1540,
    width: 400,
    height: 400,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    styles: {
      fontWeight: "bold",
      color: "#c9ab7a",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      height: 400,
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1540,
    width: 400,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "[Feedback from client]",
    styles: {
      fontWeight: "bold",
      color: "#c9ab7a",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1620,
    width: 600,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your slogan>",
    styles: {
      color: "#fff",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
    },
  },
  //end feedback
  //begin your project
  {
    type: "input",
    left: "50%",
    top: 2040,
    width: 400,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styles: {
      fontWeight: "bold",
      color: "#b3073c",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
    },
  },
  {
    type: "input",
    left: "50%",
    top: 2120,
    width: 600,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Technology used>",
    styles: {
      color: "#fff",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
    },
  },
  {
    type1: "img",
    type2: "input",
    type3: "img",
    type4: "input",
    left: 0,
    top: 2250,
    width: "100%",
    height: 300,
    id: uuid(),
    inGrid: true,
    isMulti: true,
    numberComponents: 4,
    stylesComponentMulti: {
      backgroundColor: "transparent",
    },
  },
  //end your project
  //begin footer
  {
    type: "input",
    left: "50%",
    top: 2540,
    width: 250,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Looking ForWard to working with everyone!",
    styles: {
      fontWeight: "bold",
      color: "#FFF8DC",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      lineHeight: "32px",
      textTransform: "upperCase",
    },
  },
  {
    type: "img",
    left: "50%",
    top: 2680,
    width: 200,
    height: 250,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.imgur.com/PAvCNbh.png",
    styles: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 2880,
    width: 400,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
    },
  },
  {
    type: "button",
    left: "70%",
    top: 2600,
    width: 200,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "About",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
      textTransform: "upperCase",
    },
  },
  {
    type: "input",
    left: "70%",
    top: 2680,
    width: 300,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Detail contact, number phone]",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
    },
  },

  {
    type: "a",
    left: "70%",
    top: 2880,
    width: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    href: {
      name: "facebook",
      href: "#",
    },
    valueItem: "[Detail contact, number phone]",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: 14,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
  },
  {
    type: "a",
    left: "80%",
    top: 2880,
    width: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    href: {
      name: "Instagram",
      href: "#",
    },
    valueItem: "[Detail contact, number phone]",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: 14,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
  },
  {
    type: "a",
    left: "90%",
    top: 2880,
    width: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    href: {
      name: "Youtube",
      href: "#",
    },
    valueItem: "[Detail contact, number phone]",
    styles: {
      fontWeight: "bold",
      color: "#FFF",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: 14,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
    },
  },

  //end footer
];
