export const constantActions = {
  SET_BACKGROUND_COLOR: "set_background_color",
  SET_BORDER_COLOR: "set_border_color",
  SET_BORDER_RADIUS: "set_border_radius",
  SET_BORDER_STYLE: "set_border_style",
  SET_BORDER_SIZE: "set_border_size",
  SET_HEIGHT: "set_height",
  SET_LINE_HEIGHT: "set_line_height",
  SET_COLOR: "set_color",
  SET_FONT_SIZE: "set_font_size",
  SET_FONT_FAMILY: "set_font_family",
  SET_FONT_WEIGHT: "set_font_weight",
  SET_TEXT_ALIGN: "set_align_center",
  SET_TEXT_TRANSFORM: "set_text_transform",
  SET_ID_ITEM: "set_id",
  SET_SRC: "set_src",
  SET_HREF: "set_href",
  SET_VALUE: "set_value",
};
