import uuid from "react-uuid";
import backGroundHeader02 from "~/assets/img/backGroundHeader02.png";
import {
  GrFacebookOption,
  GrInstagram,
  GrGithub,
  GrLinkedin,
  GrYoutube,
} from "react-icons/gr";

const leftDefaultText = 50;
const leftDefaultTitle = 100;

export const DefaultItemInGridTemplate3 = [
  //header

  //about

  //projects

  //eduction

  // other project

  //footer

  //end open each part in portfolio
  //begin header
  {
    type: "img",
    left: "50%",
    top: 100,
    width: 600,
    height: 250,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/F5445KH/icon-removebg-preview.png",
    styleDefault: {
      backgroundColor: "transparent",
      borderColor: "transparent",
    },
  },
  {
    type: "input",
    left: "70%",
    top: 380,
    width: 500,
    height: 80,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<About>",
    center: true,
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#000",
      fontFamily: "Poppins",
      lineHeight: "26px",
      border: "1px solid #ccc",
      boxShadow: "14px 17px 115px 0px rgba(0,0,0,0.75)",
      zIndex: -100,
    },
  },
  {
    type: "button",
    left: "50%",
    top: 12,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    center: true,
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#000",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
    },
  },
  {
    type: "input",
    left: "10%",
    top: 100,
    width: 400,
    height: 50,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      border: "none",
      color: "rgb(255, 0, 255)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      border: "3px outset  rgb(255, 69, 0)",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
      borderRadius: "100px",
      fontWeight: "bold",
      textTransform: "uppercase",
    },
  },
  {
    type: "input",
    left: "70%",
    top: 300,
    width: 500,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    center: true,
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "#800000",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "20px",
      border: "1px outset  rgb(255, 69, 0)",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
    },
  },

  //end header
  //begin about
  {
    type: "img",
    left: leftDefaultText + 150,
    top: 560,
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/CnXLkqg/Pngtree-cartoon-hand-drawn-online-education-4986516.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
    },
  },
  {
    type: "button",
    left: "55%",
    top: 650,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "#6A5ACD",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "UpperCase",
      border: "3px outset #DC143C",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  {
    type: "input",
    left: "40%",
    top: 740,
    width: 500,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      // border: "none",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  //end about
  //begin projects
  {
    type: "input",
    left: "50%",
    top: 1040,
    width: 400,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styleDefault: {
      fontWeight: "bold",
      color: "#6A5ACD",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
      textTransform: "uppercase",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1120,
    width: 600,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  {
    typeChild: ["img", "input"],
    styleDefaultChild: [
      {
        backgroundColor: "transparent",
      },
      {
        backgroundColor: "transparent",
        fontSize: 14,
      },
    ],
    left: 0,
    top: 1200,
    width: "100%",
    height: 450,
    id: uuid(),
    idChild: [uuid(), uuid(), uuid(), uuid(), uuid(), uuid(), uuid(), uuid()],
    inGrid: true,
    isMulti: true,
    numberComponents: 8,
    styleDefault: {
      backgroundColor: "#FFC0CB",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  //end projects
  //begin education
  {
    type: "img",
    left: "50%",
    top: 1520,
    width: 300,
    height: 350,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/KzzV8qS/Pngtree-network-education-online-education-illustration-6187862.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
    },
  },
  {
    type: "input",
    left: leftDefaultTitle,
    top: 1540,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Education",
    styleDefault: {
      fontWeight: "bold",
      color: "#c9ab7a",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 1620,
    width: 300,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Details major>",
    styleDefault: {
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  {
    type: "input",
    left: "70%",
    top: 1540,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About work",
    styleDefault: {
      fontWeight: "bold",
      color: "#c9ab7a",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "input",
    left: "65%",
    top: 1620,
    width: 300,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Details work>",
    styleDefault: {
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1900,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Your feeling>",
    styleDefault: {
      color: "#ccc",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
    },
  },
  //end education
  //begin other project
  {
    type: "input",
    left: "62%",
    top: 2040,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Other projects",
    styleDefault: {
      fontWeight: "bold",
      color: "#b3073c",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "img",
    left: leftDefaultText,
    top: 2120,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      border: "3px outset  rgb(255, 69, 0)",
    },
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      border: "3px outset  rgb(255, 69, 0)",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
    },
  },
  {
    type: "img",
    left: 200 + leftDefaultText + 24,
    top: 2080,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      border: "3px outset  rgb(255, 69, 0)",
    },
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
    },
  },
  {
    type: "img",
    left: 200 + leftDefaultText + 24,
    top: 2250,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      border: "3px outset  rgb(255, 69, 0)",
    },
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
    },
  },

  {
    type: "input",
    left: "60%",
    top: 2140,
    width: 250,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Technology used>",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 2240,
    width: 270,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Field of work>",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 2340,
    width: 370,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Describes>",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "12px",
    },
  },
  //end other project
  //begin footer
  {
    type: "input",
    left: "50%",
    top: 2540,
    width: 250,
    height: 50,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Contact me",
    styleDefault: {
      fontWeight: "bold",
      color: "#b3073c",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "img",
    left: "50%",
    top: 2680,
    width: 300,
    height: 250,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/dg8wwp3/Pngtree-contact-us-flat-design-style-5874427.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 2680,
    width: 250,
    height: 230,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
      borderRadius: 24,
    },
  },
  {
    type: "button",
    left: "70%",
    top: 2700,
    width: 250,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Your social networks>",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
      borderRadius: 24,
    },
  },

  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: "70%",
    top: 2850,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Facebook",
      Component: <GrFacebookOption />,
    },
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: "76%",
    top: 2850,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Instagram",
      Component: <GrInstagram />,
    },
    styleDefault: {
      color: "#FF3399",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: "82%",
    top: 2850,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Github",
      Component: <GrGithub />,
    },
    styleDefault: {
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: "88%",
    top: 2850,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Youtube",
      Component: <GrYoutube />,
    },
    styleDefault: {
      color: "red",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },

  //end footer
];
