import uuid from "react-uuid";
import {
  GrFacebookOption,
  GrInstagram,
  GrGithub,
  GrLinkedin,
  GrYoutube,
} from "react-icons/gr";
import { GoNoNewline } from "react-icons/go";

const leftDefaultText = 50;
const leftDefaultTitle = 100;

export const DefaultItemInGridTemplate4 = [
  //header

  //about

  //projects

  //eduction

  // other project

  //footer

  //end open each part in portfolio
  //begin header
  {
    type: "div",
    left: 0,
    top: 0,
    width: "100%",
    height: 500,
    id: uuid(),
    inGrid: true,
    isMulti: false,

    styleDefault: {
      backgroundColor: "#012241",
      border: "none",
      borderColor: "#cde4cf",
    },
  },

  {
    type: "input",
    left: "10%",
    top: 100,
    width: 300,
    height: 30,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter name]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      border: "none",
      color: "#fff",
      fontFamily: "Poppins",
      lineHeight: "26px",
      textTransform: "uppercase",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 160,
    width: 400,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "<Your about>",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: 18,
      textAlign: "center",
      border: "none",
      color: "blue",
      fontFamily: "Poppins",
      lineHeight: "26px",
    },
  },
  {
    type: "img",
    left: "60%",
    top: 100,
    width: 300,
    height: 300,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "transparent",
      borderColor: "transparent",
      borderRadius: "24px",
      border: "none",
    },
  },

  //end header
  //begin education
  {
    type: "div",
    left: 0,
    top: 498,
    width: "100%",
    height: 504,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "#ffd230",
      border: "none",
      borderColor: "#cde4cf",
    },
  },
  {
    type: "button",
    left: "50%",
    top: 550,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Education",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "#fff",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 650,
    width: 500,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      fontWeight: "bold",
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
    },
  },
  //end education
  //begin skills
  {
    type: "div",
    left: 0,
    top: 998,
    width: "100%",
    height: 504,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "#012241",
      border: "none",
      borderColor: "#cde4cf",
    },
  },
  {
    type: "button",
    left: leftDefaultTitle + 150,
    top: 1050,
    width: 200,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Skills",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "var(--primary)",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
    },
  },
  {
    type: "input",
    left: leftDefaultTitle + 100,
    top: 1150,
    width: 350,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<List skills>",
    styleDefault: {
      fontWeight: "bold",
      color: "#fff",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
    },
  },
  //end skills
  //begin projects
  {
    type: "div",
    left: 0,
    top: 1500,
    width: "100%",
    height: 504,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "#ffd230",
      border: "none",
      borderColor: "#cde4cf",
    },
  },
  {
    type: "button",
    left: "58%",
    top: 1550,
    width: 300,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Your projects",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "#fff",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 1650,
    width: 350,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Project theme>",
    styleDefault: {
      fontWeight: "bold",
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
    },
  },
  {
    type: "img",
    left: leftDefaultTitle,
    top: 1610,
    width: 200,
    height: 204,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderColor: "#cde4cf",
      borderRadius: "24px",
      backgroundColor: "transparent",
    },
  },
  //end projects
  //begin other project
  {
    type: "div",
    left: 0,
    top: 2000,
    width: "100%",
    height: 510,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "Experiences",
    styleDefault: {
      fontWeight: "bold",
      color: "#fff",
      backgroundColor: "#012241",
      border: "none",
    },
  },
  {
    type: "img",
    left: leftDefaultText + 100,
    top: 2150,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
    },
  },
  {
    type: "img",
    left: "50%",
    top: 2040,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
    },
  },
  {
    type: "img",
    left: "50%",
    top: 2320,
    width: 200,
    height: 150,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
    },
  },

  {
    type: "input",
    left: leftDefaultText + 100,
    top: 2050,
    width: 250,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Experiences",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
    },
  },
  {
    type: "input",
    left: "50%",
    top: 2200,
    width: 270,
    height: 48,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About work",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
    },
  },
  {
    type: "input",
    left: leftDefaultText + 100,
    top: 2330,
    width: 300,
    height: 100,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Describes>",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "12px",
    },
  },
  //end other project
  //begin footer
  {
    type: "div",
    left: 0,
    top: 2500,
    width: "100%",
    height: 504,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    styleDefault: {
      fontWeight: "bold",
      backgroundColor: "#ffd230",
      textAlign: "center",
      border: "none",
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 2540,
    width: 250,
    height: 50,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Contact me",
    styleDefault: {
      fontWeight: "bold",
      color: "var(--primary)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 18,
    },
  },
  {
    type: "img",
    left: "60%",
    top: 2540,
    width: 300,
    height: 250,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    src: "https://i.ibb.co/rHpQj5S/Pngtree-contact-our-front-desk-5412876-1.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
    },
  },
  {
    type: "input",
    left: leftDefaultText + 250 + 40,
    top: 2540,
    width: 200,
    height: 250,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styleDefault: {
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
    },
  },
  {
    type: "button",
    left: leftDefaultText + 250 + 38,
    top: 2850,
    width: 200,
    height: 30,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "Connect with me",
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
    },
  },
  {
    type: "input",
    left: leftDefaultText,
    top: 2610,
    width: 250,
    height: 200,
    id: uuid(),
    inGrid: true,
    isMulti: false,
    valueItem: "Details",
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: 14,
    },
  },

  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: leftDefaultTitle + 220,
    top: 2930,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Facebook",
      Component: <GrFacebookOption />,
    },
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: leftDefaultTitle + 250 + 30,
    top: 2930,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Instagram",
      Component: <GrInstagram />,
    },
    styleDefault: {
      color: "#FF3399",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: leftDefaultTitle + 250 + 90,
    top: 2930,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Github",
      Component: <GrGithub />,
    },
    styleDefault: {
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },
  {
    type: "icon",
    id: uuid(),
    height: 40,
    width: 200,
    left: leftDefaultTitle + 250 + 150,
    top: 2930,
    inGrid: true,
    isMulti: false,
    InfoIcon: {
      Name: "Youtube",
      Component: <GrYoutube />,
    },
    styleDefault: {
      color: "red",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
    },
  },

  //end footer
];
